version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: alessandro
       MYSQL_DATABASE: sagde
       MYSQL_USER: alessandro
       MYSQL_PASSWORD: alessandro

   wordpress:
#     depends_on:
#       - db
     image: wordpress:latest
     volumes:
       - ./:/var/www/html
     ports:
       - "8003:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: alessandro
       WORDPRESS_DB_PASSWORD: alessandro
       WORDPRESS_DB_NAME: sagde
volumes:
    db_data: {}